general:
  clock_format_24_h: false
  weather_location_query:
    type: City
    name: Algonquin
    country: US
  temperature_unit: Metric
theme:
  shell_icon_theme: OkMaterial
  app_icon_theme: Tela-circle-dark
  theme: CatppuccinMacchiato
  matugen:
    preference: LessSaturation
    scheme_type: Fidelity
    mode: Dark
    contrast: -0.31250000000000006
bars:
  frame:
    enable_frame: true
  top_bar:
    left_widgets: []
    center_widgets: []
    right_widgets: []
  bottom_bar:
    left_widgets: []
    center_widgets: []
    right_widgets: []
  left_bar:
    top_widgets:
    - QuickSettings
    - HyprlandWorkspaces
    center_widgets:
    - HyprlandDock
    bottom_widgets:
    - RecordingIndicator
    - Tray
    - Clipboard
    - Notifications
    - AudioInput
    - AudioOutput
    - Bluetooth
    - Network
    - Battery
    - Clock
  right_bar:
    top_widgets: []
    center_widgets: []
    bottom_widgets: []
menus:
  clock_menu:
    position: Left
    widgets:
    - Calendar
    - Weather
    minimum_width: 410
  clipboard_menu:
    position: Left
    widgets:
    - Clipboard
    minimum_width: 410
  quick_settings_menu:
    position: Left
    widgets:
    - Clock
    - Network
    - Bluetooth
    - AudioOutput
    - AudioInput
    - PowerProfiles
    - Wallpaper
    - MediaPlayer
    - !Spacer
      height: 20
    - !QuickActions
      widgets:
      - AirplaneMode
      - Nightlight
      - HyprPicker
      - Settings
    - !Spacer
      height: 20
    - !QuickActions
      widgets:
      - Logout
      - Lock
      - Reboot
      - Shutdown
    minimum_width: 410
  notification_menu:
    position: Left
    widgets:
    - Notifications
    minimum_width: 410
  screenshot_menu:
    position: Left
    widgets:
    - Screenshots
    - Divider
    - ScreenRecording
    minimum_width: 410
  app_launcher_menu:
    position: Left
    widgets:
    - AppLauncher
    minimum_width: 410
  screenshare_menu:
    position: Left
  vertical_menu_expansion_type: AlwaysExpanded
notifications:
  notification_position: Right
wallpaper:
  wallpaper_dir: /home/john/workspace/Varda-Theme/wallpaper
